Repository Jrod7938/txtChangeApp, pull requests merged in 2023-11, with the labels that each got.

#86 bugFix/AccountScreen
  app/src/main/java/com/jrod7938/textchangeapp/components/Components.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/account/AccountScreenViewModel.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/home/HomeScreenViewModel.kt
Labels: bugFix

#90 txtChange Post Book Listing Screen
  .github/workflows/buildTest.yml
  app/build.gradle.kts
  app/src/main/java/com/jrod7938/textchangeapp/MainActivity.kt
  app/src/main/java/com/jrod7938/textchangeapp/components/Components.kt
  app/src/main/java/com/jrod7938/textchangeapp/model/MCondition.kt
  app/src/main/java/com/jrod7938/textchangeapp/navigation/AppNavigation.kt
  app/src/main/java/com/jrod7938/textchangeapp/navigation/AppScreens.kt
  app/src/main/java/com/jrod7938/textchangeapp/navigation/BottomNavItem.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/account/AccountScreen.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/details/BookInfoScreen.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/home/HomeScreen.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/search/BookSearchScreenViewModel.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/search/SearchType.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/sell/ListingSubmissionData.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/sell/SellScreenViewModel.kt
Labels: enhancement

#94 Sprint 3
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/buildTest.yml
  .github/workflows/publishDocs.yml
  .idea/deploymentTargetDropDown.xml
  CONTRIBUTING.md
  app/build.gradle.kts
  app/src/main/java/com/jrod7938/textchangeapp/MainActivity.kt
  app/src/main/java/com/jrod7938/textchangeapp/components/Components.kt
  app/src/main/java/com/jrod7938/textchangeapp/model/MCondition.kt
  app/src/main/java/com/jrod7938/textchangeapp/model/SearchType.kt
  app/src/main/java/com/jrod7938/textchangeapp/model/SelectionType.kt
  app/src/main/java/com/jrod7938/textchangeapp/model/ToggleButtonOption.kt
  app/src/main/java/com/jrod7938/textchangeapp/navigation/AppNavigation.kt
  app/src/main/java/com/jrod7938/textchangeapp/navigation/BottomNavItem.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/account/AccountScreen.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/account/AccountScreenViewModel.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/details/BookInfoScreenViewModel.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/home/HomeScreen.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/login/LoginScreen.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/login/LoginScreenViewModel.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/search/BookSearchScreen.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/search/BookSearchScreenViewModel.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/search/SearchType.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/sell/ListingSubmissionData.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/sell/SellScreenViewModel.kt
  app/src/main/java/com/jrod7938/textchangeapp/screens/splash/SplashScreen.kt
  build.gradle.kts
Labels: documentation, enhancement, bugFix
